version: '3.9'

services:
  chroma:
    image: chromadb/chroma:latest
    volumes:
      - chroma-data:/chroma/data
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.basic_authn.BasicAuthenticationServerProvider
      - CHROMA_SERVER_AUTHN_CREDENTIALS=${CHROMA_USERNAME}:${CHROMA_PASSWORD}
      - CHROMA_SERVER_AUTHN_ENABLED=${CHROMA_AUTH_ENABLED}
      - ALLOWED_ORIGINS=*
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  chroma-data:
    driver: local
